# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0dff84335fa53755ab1bb4eb4fdebd78e5628937f1c182c02932e29a751c2f37d01397b7be8937c50c88c56aff559cea09e1ba731496cfcd768cfbc2111431ed

test:
  secret_key_base: 0a03ae1b1677b90aa05d6ba03aa7003acac17d6cef5cdd46772c8de4e5e8d97680dbeccb58e394d7053ce83117044e244804bb385dc51b4f50b4d6c91f1741d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
